spring:
  application:
    name: graphql-playground
  graphql:
    schema:
      locations: classpath:graphql/lec12
    graphql:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql


